#!/usr/bin/env python3
"""Render the presentation-only benchmark index; never evaluate or rank models."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper/generated/benchmark_scorecards"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    coverage = [
        ("DROID", "Recorded robot forecasting", "Native MSE, h10", "8 predictors; development", r"\ref{tab:editorial-spatial}"),
        ("IWS PushT", "Recorded pushing forecast", "MSE / MAE / L1 / cosine", "4 predictors; development", r"\ref{tab:iws-secondary}"),
        ("IWS Box", "Recorded bimanual forecast", "MSE / MAE / L1 / cosine", "4 predictors; development", r"\ref{tab:iws-secondary}"),
        ("IWS Rope", "Recorded deformable forecast", "MSE / MAE / L1 / cosine", "4 predictors; development", r"\ref{tab:iws-secondary}"),
        ("Sim. PushT", "Closed-loop goal reaching", "Success; MSE@1/3/5", "6 predictors; original test", r"\ref{app:original-context-study}"),
        ("Sim. Reacher", "Closed-loop goal reaching", "Success; MSE@1/3/5", "6 predictors; original test", r"\ref{app:original-context-study}"),
        ("Sim. drone", "Planar flight goal reaching", "Success; MSE@5", "6 configurations + 2 revisions; development", r"\ref{sec:domain-extensions}"),
        ("Sim. tissue", "Tissue-point goal reaching", "Success; MSE@5", "6 configurations; development", r"\ref{sec:domain-extensions}"),
        ("Open-H", "Physical-phantom input audit", "No performance metric", "0 evaluated methods", r"\ref{app:comparison-inventory}"),
    ]
    external = [
        ("PushT / Reacher", "Frozen LeWM", "Success; forecast MSE", "Completed in historical grid; separate upstream check"),
        ("PushT", "AdaJEPA", "Success under matched budget", "Official reproduction complete; matched comparison pending"),
        ("PushT / Reacher", "DINO-WM; PLDM", "Success; forecast MSE", "Not run; match visual inputs and planner budget"),
        ("Drone", "PPO; PID", "Success; physical error; failures", "Not run; disclose privileged state inputs if used"),
        ("Tissue", "LapGym PPO", "Success; goal distance; failures", "Not run; match task and observation contract"),
        ("DROID", "LeWM / DINO-WM-style predictors", "Feature MSE by horizon", "Not run under current forecast contract"),
        ("IWS PushT / Box / Rope", "RLA-WM", "Common-coordinate feature error", "Not run; resolve backbone access and representation mismatch"),
    ]
    prefix = r"""% Generated by render_comparison_inventory.py; no performance values are inferred.
\begin{table}[!htb]\centering\small
\setlength{\tabcolsep}{3pt}\renewcommand{\arraystretch}{1.10}
"""
    tex = prefix + r"""\begin{tabular}{@{}p{.13\linewidth}p{.23\linewidth}p{.23\linewidth}p{.32\linewidth}@{}}
\toprule Benchmark & Task & Reported metrics & Completed comparison / location \\ \midrule
"""
    for task, description, metrics, scope, label in coverage:
        tex += f"{task} & {description} & {metrics} & {scope}; {label} \\\\\n"
    tex += r"""\bottomrule\end{tabular}
\caption{\textbf{Benchmark and result-table index.} Counts include ours and internal
ablations, but exclude repeated seeds. DROID and IWS use the current spatial model;
the simulations use the historical context model. Drone/tissue have three method
families on two backbones; their final model tests remain pending. IWS has four
fully reported predictors per task; the separately registered unbounded component
study is reported only after its complete-campaign gate passes. MSE/MAE/L1/cosine
are feature errors (lower is better); success is higher is better. Open-H is an
input illustration, not an evaluated forecasting benchmark.}
\label{tab:comparison-coverage}\end{table}
"""
    plan = prefix + r"""\begin{tabular}{@{}p{.15\linewidth}p{.23\linewidth}p{.22\linewidth}p{.31\linewidth}@{}}
\toprule Benchmark & External method & Target metrics & Execution status / required match \\ \midrule
"""
    for row in external:
        plan += " & ".join(row) + " \\\\\n"
    plan += r"""\bottomrule\end{tabular}
\caption{\textbf{External-comparison completion plan for this research draft.}
Named candidates are not claimed as completed baselines. Internal controls and
component ablations remain in the numerical tables. AdaJEPA uses different inputs
and planning settings in its completed reproduction. RLA-WM uses a different
feature representation; native scores are not interchangeable with ours. There is
currently no completed matched external-method comparison for the spatial
recorded-video model. Pending cells are unavailable, not zero performance.}
\label{tab:comparison-pending}\end{table}
"""
    sources = ["reports/benchmark_metrics_and_comparators_2026-09-20.md",
               "paper/sections/main_evaluation.tex", "paper/sections/domain_extensions.tex",
               "paper/sections/appendix/simulation_protocols.tex"]
    manifest = {
        "schema": "shiftwm_presentation_comparison_index_v1",
        "scope": "reporting_inventory_not_experiment_registration",
        "coverage": [dict(zip(("benchmark", "task", "metrics", "completed_scope", "location"), r)) for r in coverage],
        "external_plan": [dict(zip(("benchmark", "method", "target_metrics", "status"), r)) for r in external],
        "sources": {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in sources},
    }
    for name, content in (("coverage.tex", tex), ("external_plan.tex", plan),
                          ("inventory.json", json.dumps(manifest, indent=2) + "\n")):
        path = OUT / name
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
    print(json.dumps({"status": "rendered", "benchmarks_evaluated": 8, "input_audits": 1}))


if __name__ == "__main__":
    main()
