"""Segmentation view of the forecasts (results/v2/analysis/segments, from scripts/v2/segments.py).

Top: two held-out DROID windows (fixed rule, see segments.py). Columns: observed frame t with the SAM 2.1 arm mask and
the ShiftWM transport field on the predicted arm (arrows: source -> target, k=10); the true frame t+10 with its tracked
SAM mask; the arm mask read out of each method's k=10 forecast (nearest-prototype labelling of the forecast DINOv2
features), drawn as a smooth contour on the true future frame, with its IoU against the SAM mask (best in green bold).
Bottom: arm-mask IoU vs. horizon for all methods (95% bootstrap CIs over test episodes), all windows and moving-arm
windows. Also writes tables/generated/segments_numbers.tex (macros quoted in the text).
"""
import json
from pathlib import Path
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import patheffects as pe
from matplotlib.colors import to_rgb
import numpy as np
from scipy.interpolate import RectBivariateSpline

sys.path.insert(0, str(Path(__file__).parent))
import make_figures as mf  # noqa: E402

D = mf.RES / "analysis/segments"
NUMS = mf.ROOT / "paper/submission_folder/tables/generated/segments_numbers.tex"
SAMC = "#F2A900"          # SAM (reference) mask colour
G = 16


def smooth(score, h, w):
    """16x16 patch score -> [h,w] bicubic spline through the patch centres (the encoder squashes the frame)."""
    yc = (np.arange(G) + 0.5) * h / G - 0.5; xc = (np.arange(G) + 0.5) * w / G - 0.5
    sp = RectBivariateSpline(yc, xc, score.reshape(G, G), kx=3, ky=3)
    return sp(np.arange(h), np.arange(w))


def tint(ax, mask, color, alpha):
    rgba = np.zeros(mask.shape + (4,)); rgba[..., :3] = to_rgb(color); rgba[..., 3] = mask * alpha
    ax.imshow(rgba, aspect="equal", interpolation="antialiased")


def outline(ax, field, color, lw, ls="-", level=0.5):
    ax.contour(field, levels=[level], colors=[color], linewidths=lw, linestyles=[ls])


def label(ax, text, color="white", bold=False, loc="lr"):
    x, ha = (0.97, "right") if loc[1] == "r" else (0.03, "left")
    ax.text(x, 0.05, text, transform=ax.transAxes, ha=ha, va="bottom", fontsize=6.3, color=color,
            fontweight="bold" if bold else "normal", bbox=dict(fc="#1F2A37", ec="none", alpha=0.72, pad=0.9))


def arrows(ax, off, gate, sel, h, w, n=7):
    """Few clean arrows: source (q + expected source offset) -> query q, on the strongest-moving selected patches."""
    mag = np.linalg.norm(off, axis=-1) * gate
    cand = [i for i in np.argsort(-mag) if sel[i] and mag[i] > 0.25]
    chosen = []
    for i in cand:
        yi, xi = divmod(i, G)
        if all(max(abs(yi - divmod(j, G)[0]), abs(xi - divmod(j, G)[1])) >= 3 for j in chosen):
            chosen.append(i)
        if len(chosen) == n:
            break
    sx, sy = w / G, h / G
    for i in chosen:
        yi, xi = divmod(i, G)
        qx, qy = (xi + 0.5) * sx, (yi + 0.5) * sy
        px, py = qx + off[i, 0] * sx, qy + off[i, 1] * sy
        a = ax.annotate("", xy=(qx, qy), xytext=(px, py),
                        arrowprops=dict(arrowstyle="-|>,head_length=0.35,head_width=0.2", color=mf.METHODS["shiftwm"][1],
                                        lw=1.1, shrinkA=0, shrinkB=0))
        a.arrow_patch.set_path_effects([pe.Stroke(linewidth=2.2, foreground="white"), pe.Normal()])


def write_numbers(S):
    p = S["primary_labeller"]; R = S["results"][p]
    k10 = lambda sub, n, key="mean": R[sub][n][key][-1]
    lines = ["% generated by paper/submission_folder/figures/src/make_segments.py from results/v2/analysis/segments"]
    tag = {"shiftwm": "SW", "direct": "Di", "ar": "AR", "persistence": "Pers", "oracle": "Oracle"}
    for sub, pre in (("all", "segIoU"), ("moving", "segMovIoU")):
        for n, t in tag.items():
            lines.append(f"\\newcommand{{\\{pre}{t}}}{{{k10(sub, n):.2f}}}")
            lines.append(f"\\newcommand{{\\{pre}{t}One}}{{{R[sub][n]['mean'][0]:.2f}}}")
            lines.append(f"\\newcommand{{\\{pre}{t}Five}}{{{R[sub][n]['mean'][4]:.2f}}}")
        for n in ("direct", "ar", "persistence"):
            d = R[sub][n]["diff_sw_minus"]
            lines.append(f"\\newcommand{{\\{pre}Diff{tag[n]}}}{{{100 * d['mean'][-1]:+.1f}}}")
            lines.append(f"\\newcommand{{\\{pre}Diff{tag[n]}CI}}{{[{100 * d['lo'][-1]:+.1f}, {100 * d['hi'][-1]:+.1f}]}}")
    lines += [f"\\newcommand{{\\segWindows}}{{{R['all']['windows']:,}}}".replace(",", "{,}"),
              f"\\newcommand{{\\segMovWindows}}{{{R['moving']['windows']:,}}}".replace(",", "{,}"),
              f"\\newcommand{{\\segEpisodes}}{{{R['all']['episodes']}}}",
              f"\\newcommand{{\\segTracked}}{{{S['windows_tracked']:,}}}".replace(",", "{,}"),
              f"\\newcommand{{\\segTotal}}{{{S['windows_total']:,}}}".replace(",", "{,}"),
              f"\\newcommand{{\\segStride}}{{{S['window_stride']}}}",
              f"\\newcommand{{\\segLabeller}}{{{ {'nn': 'nearest-neighbour', 'multi': 'multi-prototype', 'proto': 'prototype'}[p] }}}"]
    for l, v in S["oracle_iou_k10_by_labeller"].items():
        lines.append(f"\\newcommand{{\\segOracle{l.capitalize()}}}{{{v:.2f}}}")
    NUMS.parent.mkdir(parents=True, exist_ok=True)
    NUMS.write_text("\n".join(lines) + "\n")


def iou_plot(ax, R, sub, title):
    K = len(R[sub]["shiftwm"]["mean"]); k = np.arange(1, K + 1)
    order = ("persistence", "ar", "direct", "shiftwm")
    for n in order:
        lab, col, ls, mk = mf.METHODS[n]
        r = R[sub][n]
        ax.plot(k, r["mean"], color=col, ls=ls, marker=mk, markevery=3, lw=1.8 if n == "shiftwm" else 1.2,
                label=lab.split(" (")[0] if n != "shiftwm" else "ShiftWM", zorder=3 if n == "shiftwm" else 2)
        ax.fill_between(k, r["lo"], r["hi"], color=col, alpha=0.13, lw=0)
    ax.plot(k, R[sub]["oracle"]["mean"], color=mf.INK, ls=":", lw=1.0, label="true future features")
    ax.set_xticks([1, 5, 10]); ax.set_xlim(0.7, K + 0.3)
    ax.set_xlabel("forecast step $k$", fontsize=6.8, labelpad=1); ax.tick_params(labelsize=6.3, pad=1.5)
    ax.set_title(title, fontsize=7.2, pad=2.5, loc="left")


def main():
    if not (D / "summary.json").exists():
        fig, ax = plt.subplots(figsize=(5.5, 2.6)); mf.pending(ax, "segmentation view"); fig.savefig(mf.FIG / "segments.pdf"); return
    S = json.loads((D / "summary.json").read_text()); Z = np.load(D / "examples.npz", allow_pickle=True)
    write_numbers(S)
    R = S["results"][S["primary_labeller"]]
    names = list(Z["names"]); H = int(Z["history"]); K = Z["score"].shape[2]
    fig = plt.figure(figsize=(5.5, 2.72))
    top = fig.add_gridspec(2, 5, left=0.005, right=0.995, top=0.93, bottom=0.44, wspace=0.03, hspace=0.06)
    cols = ["observed $t$ + transport", "true $t{+}10$ (SAM 2.1)", "ShiftWM (ours)", "Direct", "AR"]
    for r in range(2):
        frames, masks = Z["frames"][r], Z["masks"][r]
        obs, fut = frames[H - 1], frames[H - 1 + K]
        h, w = obs.shape[:2]
        ious = {n: float(Z["iou"][r][names.index(n)][K - 1]) for n in names}
        best = max(("shiftwm", "direct", "ar"), key=lambda n: ious[n])
        # (1) observed frame, SAM mask at t, ShiftWM transport on its predicted arm patches
        ax = fig.add_subplot(top[r, 0]); ax.imshow(obs, aspect="equal")
        tint(ax, masks[0], SAMC, 0.38); outline(ax, masks[0].astype(float), SAMC, 0.7)
        sel = Z["score"][r][names.index("shiftwm")][K - 1] > 0
        arrows(ax, Z["offsets"][r][K - 1], Z["gate"][r][K - 1], sel, h, w)
        # (2) true future with tracked SAM mask
        ax2 = fig.add_subplot(top[r, 1]); ax2.imshow(fut, aspect="equal")
        tint(ax2, masks[K], SAMC, 0.38); outline(ax2, masks[K].astype(float), SAMC, 0.7)
        label(ax2, f"moved: {100 * float(Z['motion'][r]):.0f}% of arm", loc="lr")
        axes = [ax, ax2]
        for c, n in enumerate(("shiftwm", "direct", "ar")):
            a = fig.add_subplot(top[r, 2 + c]); a.imshow(fut, aspect="equal")
            col = mf.METHODS[n][1]
            f = smooth(Z["score"][r][names.index(n)][K - 1], h, w)
            tint(a, f > 0, col, 0.42); outline(a, f, col, 1.0, level=0.0)
            outline(a, masks[K].astype(float), "white", 0.6, ls=(0, (2, 1.5)))
            label(a, f"IoU {ious[n]:.2f}", color="#7CF2C4" if n == best else "white", bold=n == best)
            axes.append(a)
        for c, a in enumerate(axes):
            a.set_xticks([]); a.set_yticks([]); a.set_xlim(-0.5, w - 0.5); a.set_ylim(h - 0.5, -0.5)
            for sp in a.spines.values():
                sp.set_visible(False)
            if r == 0:
                a.set_title(cols[c], fontsize=7, pad=2.5,
                            color=mf.METHODS["shiftwm"][1] if c == 2 else mf.INK)
    bot = fig.add_gridspec(1, 3, left=0.075, right=0.995, top=0.345, bottom=0.085, wspace=0.28, width_ratios=[1, 1, 0.78])
    a1 = fig.add_subplot(bot[0]); iou_plot(a1, R, "all", f"(b) arm IoU, all {R['all']['windows']} windows")
    a1.set_ylabel("arm IoU", fontsize=6.8, labelpad=1.5)
    a2 = fig.add_subplot(bot[1], sharey=a1); iou_plot(a2, R, "moving", "(c) moving-arm windows")
    lo = min(min(R[s][n]["lo"]) for s in ("all", "moving") for n in ("persistence", "shiftwm", "direct", "ar"))
    hi = max(max(R[s]["oracle"]["hi"]) for s in ("all", "moving"))
    a1.set_ylim(np.floor(lo * 20) / 20, np.ceil(hi * 20) / 20 + 0.01)
    al = fig.add_subplot(bot[2]); al.set_axis_off()
    hs, ls = a1.get_legend_handles_labels()
    order = [3, 2, 1, 0, 4]
    al.legend([hs[i] for i in order], [ls[i] for i in order], loc="center left", fontsize=6.5, handlelength=2.0,
              borderaxespad=0, labelspacing=0.55)
    fig.text(0.005, 0.975, "(a) Robot-arm masks read out of the $k{=}10$ feature forecasts (held-out DROID)",
             fontsize=7.4, fontweight="bold", color=mf.INK, va="top")
    fig.savefig(mf.FIG / "segments.pdf"); fig.savefig(mf.FIG / "segments_preview.png", dpi=220)
    print("wrote segments")


if __name__ == "__main__":
    main()
